#include <vector>
#include <string>
#include <map>
#include <GraphInfo.h>


std::vector<std::string> getListOfZones(){
    std::vector<std::string> ans = {"Aveiro", "Beja","Braga",
                                    "Bragança","Castelo Branco","Coimbra",
                                    "Évora","Faro","Guarda",
                                    "Leiria","Lisboa","Portalegre",
                                    "Porto","Santarém","Setúbal",
                                    "Viana do Castelo","Vila Real","Viseu"
                                    };
    //std::vector<std::string> ans = {"A", "B", "C"};
    return ans;
}


std::vector<std::vector<std::string>> getListOfVertices(){
    std::vector<std::vector<std::string>> ans = {{"Águeda", "47220", "Aveiro"},
                                                {"Albergaria-a-Velha", "25779", "Aveiro"},
                                                {"Anadia", "28205", "Aveiro"},
                                                {"Arouca", "20916", "Aveiro"},
                                                {"Aveiro", "86037", "Aveiro"},
                                                {"Castelo de Paiva", "15448", "Aveiro"},
                                                {"Espinho", "32393", "Aveiro"},
                                                {"Estarreja", "27097", "Aveiro"},
                                                {"Ílhavo", "42129", "Aveiro"},
                                                {"Mealhada", "19787", "Aveiro"},
                                                {"Murtosa", "11036", "Aveiro"},
                                                {"Oliveira de Azeméis", "67227", "Aveiro"},
                                                {"Oliveira do Bairro", "25055", "Aveiro"},
                                                {"Ovar", "56735", "Aveiro"},
                                                {"Santa Maria da Feira", "139837", "Aveiro"},
                                                {"São João da Madeira", "23863", "Aveiro"},
                                                {"Sever do Vouga", "10944", "Aveiro"},
                                                {"Vagos", "24452", "Aveiro"},
                                                {"Vale de Cambra", "21251", "Aveiro"},

                                                {"Aljustrel", "8922", "Beja"},
                                                {"Almodôvar", "6694", "Beja"},
                                                {"Alvito", "2279", "Beja"},
                                                {"Barrancos", "1430", "Beja"},
                                                {"Beja", "33838", "Beja"},
                                                {"Castro Verde", "6965", "Beja"},
                                                {"Cuba", "4471", "Beja"},
                                                {"Ferreira do Alentejo", "7912", "Beja"},
                                                {"Mértola", "6137", "Beja"},
                                                {"Moura", "13320", "Beja"},
                                                {"Odemira", "33124", "Beja"},
                                                {"Ourique", "4829", "Beja"},
                                                {"Serpa", "13731", "Beja"},
                                                {"Vidigueira", "5229", "Beja"},

                                                {"Amares", "19578", "Braga"},
                                                {"Barcelos", "117005", "Braga"},
                                                {"Braga", "201583", "Braga"},
                                                {"Cabeceiras de Basto", "15560", "Braga"},
                                                {"Celorico de Basto", "17655", "Braga"},
                                                {"Esposende", "37129", "Braga"},
                                                {"Fafe", "48514", "Braga"},
                                                {"Guimarães", "156785", "Braga"},
                                                {"Póvoa de Lanhoso", "22607", "Braga"},
                                                {"Terras de Bouro", "6388", "Braga"},
                                                {"Vieira do Minho", "12066", "Braga"},
                                                {"Vila Nova de Famalicão", "135994", "Braga"},
                                                {"Vila Verde", "48150", "Braga"},
                                                {"Vizela", "24529", "Braga"},

                                                {"Alfândega da Fé", "4222", "Bragança"},
                                                {"Bragança", "35425", "Bragança"},
                                                {"Carrazeda de Ansiães", "5390", "Bragança"},
                                                {"Freixo de Espada à Cinta", "3139", "Bragança"},
                                                {"Macedo de Cavaleiros", "14236", "Bragança"},
                                                {"Miranda do Douro", "6298", "Bragança"},
                                                {"Mirandela", "21390", "Bragança"},
                                                {"Mogadouro", "8237", "Bragança"},
                                                {"Torre de Moncorvo", "6737", "Bragança"},
                                                {"Vila Flor", "6039", "Bragança"},
                                                {"Vimioso", "4176", "Bragança"},
                                                {"Vinhais", "7450", "Bragança"},

                                                {"Belmonte", "6216", "Castelo Branco"},
                                                {"Castelo Branco", "52913", "Castelo Branco"},
                                                {"Covilhã", "46375", "Castelo Branco"},
                                                {"Fundão", "26981", "Castelo Branco"},
                                                {"Idanha-a-Nova", "8492", "Castelo Branco"},
                                                {"Oleiros", "4886", "Castelo Branco"},
                                                {"Penamacor", "4797", "Castelo Branco"},
                                                {"Proença-a-Nova", "7091", "Castelo Branco"},
                                                {"Sertã", "14900", "Castelo Branco"},
                                                {"Vila de Rei", "3442", "Castelo Branco"},
                                                {"Vila Velha de Ródão", "3515", "Castelo Branco"},

                                                {"Arganil", "11313", "Coimbra"},
                                                {"Cantanhede", "34916", "Coimbra"},
                                                {"Coimbra", "144822", "Coimbra"},
                                                {"Condeixa-a-Nova", "17555", "Coimbra"},
                                                {"Figueira da Foz", "60670", "Coimbra"},
                                                {"Góis", "3800", "Coimbra"},
                                                {"Lousã", "17419", "Coimbra"},
                                                {"Mira", "12523", "Coimbra"},
                                                {"Miranda do Corvo", "12117", "Coimbra"},
                                                {"Montemor-o-Velho", "24889", "Coimbra"},
                                                {"Oliveira do Hospital", "19464", "Coimbra"},
                                                {"Pampilhosa da Serra", "4138", "Coimbra"},
                                                {"Penacova", "12919", "Coimbra"},
                                                {"Penela", "5611", "Coimbra"},
                                                {"Soure", "17555", "Coimbra"},
                                                {"Tábua", "11602", "Coimbra"},
                                                {"Vila Nova de Poiares", "7140", "Coimbra"},

                                                {"Alandroal", "4996", "Évora"},
                                                {"Arraiolos", "6778", "Évora"},
                                                {"Borba", "6398", "Évora"},
                                                {"Estremoz", "12550", "Évora"},
                                                {"Évora", "53937", "Évora"},
                                                {"Montemor-o-Novo", "15951", "Évora"},
                                                {"Mora", "4155", "Évora"},
                                                {"Mourão", "2424", "Évora"},
                                                {"Portel", "5737", "Évora"},
                                                {"Redondo", "6299", "Évora"},
                                                {"Reguengos de Monsaraz", "9875", "Évora"},
                                                {"Vendas Novas", "11537", "Évora"},
                                                {"Viana do Alentejo", "5538", "Évora"},
                                                {"Vila Viçosa", "7300", "Évora"},

                                                {"Albufeira", "47524", "Faro"},
                                                {"Alcoutim", "2413", "Faro"},
                                                {"Aljezur", "6362", "Faro"},
                                                {"Castro Marim", "6819", "Faro"},
                                                {"Faro", "69468", "Faro"},
                                                {"Lagoa", "24918", "Faro"},
                                                {"Lagos", "34552", "Faro"},
                                                {"Loulé", "74410", "Faro"},
                                                {"Monchique", "5323", "Faro"},
                                                {"Olhão", "45043", "Faro"},
                                                {"Portimão", "63079", "Faro"},
                                                {"São Brás de Alportel", "11604", "Faro"},
                                                {"Silves", "39497", "Faro"},
                                                {"Tavira", "27861", "Faro"},
                                                {"Vila do Bispo", "5935", "Faro"},
                                                {"Vila Real de Santo António", "19314", "Faro"},

                                                {"Aguiar da Beira", "5302", "Guarda"},
                                                {"Almeida", "5676", "Guarda"},
                                                {"Celorico da Beira", "6605", "Guarda"},
                                                {"Figueira de Castelo Rodrigo", "5044", "Guarda"},
                                                {"Fornos de Algodres", "4383", "Guarda"},
                                                {"Gouveia", "2938", "Guarda"},
                                                {"Guarda", "40011", "Guarda"},
                                                {"Manteigas", "2938", "Guarda"},
                                                {"Mêda", "4572", "Guarda"},
                                                {"Pinhel", "7849", "Guarda"},
                                                {"Sabugal", "11270", "Guarda"},
                                                {"Seia", "21441", "Guarda"},
                                                {"Trancoso", "8313", "Guarda"},
                                                {"Vila Nova de Foz Côa", "6369", "Guarda"},

                                                {"Alcobaça", "57358", "Leiria"},
                                                {"Alvaiázere", "6355", "Leiria"},
                                                {"Ansião", "11865", "Leiria"},
                                                {"Batalha", "16565", "Leiria"},
                                                {"Bombarral", "13990", "Leiria"},
                                                {"Caldas da Rainha", "54145", "Leiria"},
                                                {"Castanheira de Pêra", "2710", "Leiria"},
                                                {"Figueiró dos Vinhos", "5270", "Leiria"},
                                                {"Leiria", "133795", "Leiria"},
                                                {"Marinha Grande", "41011", "Leiria"},
                                                {"Nazaré", "15698", "Leiria"},
                                                {"Óbidos", "13294", "Leiria"},
                                                {"Pedrógão Grande", "3627", "Leiria"},
                                                {"Peniche", "27554", "Leiria"},
                                                {"Pombal", "52026", "Leiria"},
                                                {"Porto de Mós", "23998", "Leiria"},

                                                {"Alenquer", "48319", "Lisboa"},
                                                {"Amadora", "178523", "Lisboa"},
                                                {"Arruda dos Vinhos", "15321", "Lisboa"},
                                                {"Azambuja", "22932", "Lisboa"},
                                                {"Cadaval", "14435", "Lisboa"},
                                                {"Cascais", "219636", "Lisboa"},
                                                {"Lisboa", "567131", "Lisboa"},
                                                {"Loures", "207065", "Lisboa"},
                                                {"Lourinhã", "28383", "Lisboa"},
                                                {"Mafra", "90128", "Lisboa"},
                                                {"Odivelas", "153708", "Lisboa"},
                                                {"Oeiras", "175677", "Lisboa"},
                                                {"Sintra", "395528", "Lisboa"},
                                                {"Sobral de Monte Agraço", "11879", "Lisboa"},
                                                {"Torres Vedras", "88020", "Lisboa"},
                                                {"Vila Franca de Xira", "139452", "Lisboa"},

                                                {"Alter do Chão", "3180", "Portalegre"},
                                                {"Arronches", "2768", "Portalegre"},
                                                {"Avis", "3802", "Portalegre"},
                                                {"Campo Maior", "7916", "Portalegre"},
                                                {"Castelo de Vide", "3197", "Portalegre"},
                                                {"Crato", "3275", "Portalegre"},
                                                {"Elvas", "20412", "Portalegre"},
                                                {"Fronteira", "2974", "Portalegre"},
                                                {"Gavião", "3324", "Portalegre"},
                                                {"Marvão", "3024", "Portalegre"},
                                                {"Monforte", "3002", "Portalegre"},
                                                {"Nisa", "5685", "Portalegre"},
                                                {"Ponte de Sor", "15207", "Portalegre"},
                                                {"Portalegre", "21914", "Portalegre"},
                                                {"Sousel", "4401", "Portalegre"},

                                              {"Amarante", "52235", "Porto"},
                                                {"Baião", "17201", "Porto"},
                                                {"Felgueiras", "55429", "Porto"},
                                                {"Gondomar", "168582", "Porto"},
                                                {"Lousada", "48309", "Porto"},
                                                {"Maia", "142594", "Porto"},
                                                {"Marco de Canaveses", "49576", "Porto"},
                                                {"Matosinhos", "179558", "Porto"},
                                                {"Paços de Ferreira", "56400", "Porto"},
                                                {"Paredes", "86015", "Porto"},
                                                {"Penafiel", "70320", "Porto"},
                                                {"Porto", "248769", "Porto"},
                                                {"Póvoa de Varzim", "67525", "Porto"},
                                                {"Santo Tirso", "67826", "Porto"},
                                                {"Trofa", "39997", "Porto"},
                                                {"Valongo", "100166", "Porto"},
                                                {"Vila do Conde", "84872", "Porto"},
                                                {"Vila Nova de Gaia", "311223", "Porto"},

                                                {"Abrantes", "33811", "Santarém"},
                                                {"Alcanena", "12750", "Santarém"},
                                                {"Almeirim", "22820", "Santarém"},
                                                {"Alpiarça", "7331", "Santarém"},
                                                {"Benavente", "32323", "Santarém"},
                                                {"Cartaxo", "24359", "Santarém"},
                                                {"Chamusca", "8531", "Santarém"},
                                                {"Constância", "3958", "Santarém"},
                                                {"Coruche", "17365", "Santarém"},
                                                {"Entroncamento", "21985", "Santarém"},
                                                {"Ferreira do Zêzere", "8018", "Santarém"},
                                                {"Golegã", "5442", "Santarém"},
                                                {"Mação", "6403", "Santarém"},
                                                {"Ourém", "46512", "Santarém"},
                                                {"Rio Maior", "22315", "Santarém"},
                                                {"Salvaterra de Magos", "23337", "Santarém"},
                                                {"Santarém", "61009", "Santarém"},
                                                {"Sardoal", "3625", "Santarém"},
                                                {"Tomar", "36859", "Santarém"},
                                                {"Torres Novas", "34719", "Santarém"},
                                                {"Vila Nova da Barquinha", "7783", "Santarém"},

                                                {"Alcácer do Sal", "11082", "Setúbal"},
                                                {"Alcochete", "20101", "Setúbal"},
                                                {"Almada", "181232", "Setúbal"},
                                                {"Barreiro", "79966", "Setúbal"},
                                                {"Grândola", "14165", "Setúbal"},
                                                {"Moita", "68950", "Setúbal"},
                                                {"Montijo", "59197", "Setúbal"},
                                                {"Palmela", "72938", "Setúbal"},
                                                {"Santiago do Cacém", "28246", "Setúbal"},
                                                {"Seixal", "173163", "Setúbal"},
                                                {"Sesimbra", "55504", "Setúbal"},
                                                {"Setúbal", "123548", "Setúbal"},
                                                {"Sines", "14771", "Setúbal"},

                                                {"Arcos de Valdevez", "20859", "Viana do Castelo"},
                                                {"Caminha", "16442", "Viana do Castelo"},
                                                {"Melgaço", "7599", "Viana do Castelo"},
                                                {"Monção", "18032", "Viana do Castelo"},
                                                {"Paredes de Coura", "8709", "Viana do Castelo"},
                                                {"Ponte da Barca", "11178", "Viana do Castelo"},
                                                {"Ponte de Lima", "41130", "Viana do Castelo"},
                                                {"Valença", "14159", "Viana do Castelo"},
                                                {"Viana do Castelo", "86780", "Viana do Castelo"},
                                                {"Vila Nova de Cerveira", "9327", "Viana do Castelo"},

                                                {"Alijó", "10324", "Vila Real"},
                                                {"Boticas", "4885", "Vila Real"},
                                                {"Chaves", "37419", "Vila Real"},
                                                {"Mesão Frio", "3485", "Vila Real"},
                                                {"Mondim de Basto", "6405", "Vila Real"},
                                                {"Montalegre", "9142", "Vila Real"},
                                                {"Murça", "5256", "Vila Real"},
                                                {"Peso da Régua", "14402", "Vila Real"},
                                                {"Ribeira de Pena", "5861", "Vila Real"},
                                                {"Sabrosa", "5634", "Vila Real"},
                                                {"Santa Marta de Penaguião", "5983", "Vila Real"},
                                                {"Valpaços", "14590", "Vila Real"},
                                                {"Vila Pouca de Aguiar", "11772", "Vila Real"},
                                                {"Vila Real", "49928", "Vila Real"},

                                                {"Armamar", "5650", "Viseu"},
                                                {"Carregal do Sal", "9177", "Viseu"},
                                                {"Castro Daire", "13732", "Viseu"},
                                                {"Cinfães", "17432", "Viseu"},
                                                {"Lamego", "24129", "Viseu"},
                                                {"Mangualde", "18592", "Viseu"},
                                                {"Moimenta da Beira", "9733", "Viseu"},
                                                {"Mortágua", "9059", "Viseu"},
                                                {"Nelas", "13323", "Viseu"},
                                                {"Oliveira de Frades", "9763", "Viseu"},
                                                {"Penalva do Castelo", "7342", "Viseu"},
                                                {"Penedono", "2804", "Viseu"},
                                                {"Resende", "9762", "Viseu"},
                                                {"Santa Comba Dão", "9059", "Viseu"},
                                                {"São João da Pesqueira", "6772", "Viseu"},
                                                {"São Pedro do Sul", "15197", "Viseu"},
                                                {"Sátão", "11138", "Viseu"},
                                                {"Sernancelhe", "5793", "Viseu"},
                                                {"Tabuaço", "5052", "Viseu"},
                                                {"Tarouca", "7615", "Viseu"},
                                                {"Tondela", "25824", "Viseu"},
                                                {"Vila Nova de Paiva", "4753", "Viseu"},
                                                {"Viseu", "101977", "Viseu"},
                                                {"Vouzela", "9765", "Viseu"}
                                            };
    /*std::vector<std::vector<std::string>> ans = {
                                                // weight = 31
                                                {"1", "10", "A" },
                                                {"2", "5", "A" },
                                                {"3", "15", "A" },
                                                {"4", "1", "A" },
                                                // weight = 21
                                                {"5", "8", "B" },
                                                {"6", "7", "B" },
                                                {"7", "6", "B" },
                                                // weight = 9
                                                {"8", "2", "C" },
                                                {"9", "3", "C" },
                                                {"10", "4", "C" },
    };*/
    return ans;
}


std::map<std::string, std::vector<std::string>> mapOfNeigh(){
    std::map<std::string, std::vector<std::string>> neighbors = {
        // District of Aveiro
        {"Águeda", {"Anadia", "Aveiro", "Oliveira do Bairro", "Oliveira de Azeméis", "Sever do Vouga"}},
        {"Albergaria-a-Velha", {"Aveiro", "Estarreja", "Sever do Vouga", "Oliveira de Azeméis"}},
        {"Anadia", {"Águeda", "Mealhada", "Oliveira do Bairro"}},
        {"Arouca", {"Castelo de Paiva", "Oliveira de Azeméis", "Santa Maria da Feira", "Vale de Cambra"}},
        {"Aveiro", {"Águeda", "Albergaria-a-Velha", "Ílhavo", "Murtosa", "Oliveira do Bairro", "Estarreja", "Vagos"}},
        {"Castelo de Paiva", {"Arouca", "Santa Maria da Feira", "Penafiel"}},
        {"Espinho", {"Santa Maria da Feira", "Vila Nova de Gaia"}},
        {"Estarreja", {"Albergaria-a-Velha", "Aveiro", "Murtosa", "Ovar"}},
        {"Ílhavo", {"Aveiro", "Vagos"}},
        {"Mealhada", {"Anadia", "Cantanhede", "Coimbra", "Mortágua", "Penacova"}},
        {"Murtosa", {"Aveiro", "Estarreja", "Ovar"}},
        {"Oliveira de Azeméis", {"Águeda", "Albergaria-a-Velha", "Arouca", "Santa Maria da Feira", "Vale de Cambra", "Sever do Vouga", "São João da Madeira"}},
        {"Oliveira do Bairro", {"Águeda", "Anadia", "Aveiro"}},
        {"Ovar", {"Estarreja", "Murtosa", "Santa Maria da Feira"}},
        {"Santa Maria da Feira", {"Arouca", "Espinho", "Oliveira de Azeméis", "Ovar", "Vila Nova de Gaia", "Castelo de Paiva", "São João da Madeira", "Vale de Cambra"}},
        {"São João da Madeira", {"Santa Maria da Feira", "Oliveira de Azeméis"}},
        {"Sever do Vouga", {"Águeda", "Albergaria-a-Velha", "Oliveira de Azeméis", "Vale de Cambra"}},
        {"Vagos", {"Ílhavo", "Aveiro", "Mira"}},
        {"Vale de Cambra", {"Arouca", "Oliveira de Azeméis", "Santa Maria da Feira", "Sever do Vouga"}},

        // District of Beja
        {"Aljustrel", {"Almodôvar", "Castro Verde", "Ourique", "Beja", "Ferreira do Alentejo"}},
        {"Almodôvar", {"Aljustrel", "Castro Verde", "Ourique", "Odemira", "Mértola"}},
        {"Alvito", {"Beja", "Ferreira do Alentejo", "Cuba", "Viana do Alentejo"}},
        {"Barrancos", {"Moura", "Mértola"}},
        {"Beja", {"Aljustrel", "Alvito", "Cuba", "Ferreira do Alentejo", "Mértola", "Serpa", "Vidigueira"}},
        {"Castro Verde", {"Aljustrel", "Almodôvar", "Ourique", "Mértola"}},
        {"Cuba", {"Beja", "Vidigueira", "Alvito", "Ferreira do Alentejo"}},
        {"Ferreira do Alentejo", {"Beja", "Aljustrel", "Alvito", "Cuba"}},
        {"Mértola", {"Beja", "Castro Verde", "Almodôvar", "Odemira", "Serpa", "Barrancos", "Alcoutim"}},
        {"Moura", {"Barrancos", "Serpa", "Vidigueira"}},
        {"Odemira", {"Almodôvar", "Ourique", "Santiago do Cacém", "Sines", "Grândola", "Mértola", "Aljezur", "Monchique", "Silves"}},
        {"Ourique", {"Aljustrel", "Almodôvar", "Castro Verde", "Odemira"}},
        {"Serpa", {"Beja", "Moura", "Mértola"}},
        {"Vidigueira", {"Beja", "Cuba", "Moura"}},

        // District of Braga
        {"Amares", {"Braga", "Póvoa de Lanhoso", "Terras de Bouro", "Vila Verde", "Vieira do Minho"}},
        {"Barcelos", {"Braga", "Esposende", "Póvoa de Varzim", "Vila Nova de Famalicão", "Viana do Castelo"}},
        {"Braga", {"Amares", "Barcelos", "Póvoa de Lanhoso", "Vila Nova de Famalicão", "Vila Verde", "Guimarães", "Mondim de Basto"}},
        {"Cabeceiras de Basto", {"Celorico de Basto", "Fafe", "Mondim de Basto", "Vieira do Minho"}},
        {"Celorico de Basto", {"Amarante", "Felgueiras", "Fafe", "Mondim de Basto", "Cabeceiras de Basto"}},
        {"Esposende", {"Barcelos", "Póvoa de Varzim", "Viana do Castelo"}},
        {"Fafe", {"Cabeceiras de Basto", "Celorico de Basto", "Felgueiras", "Guimarães", "Póvoa de Lanhoso", "Vizela"}},
        {"Guimarães", {"Braga", "Fafe", "Póvoa de Lanhoso", "Santo Tirso", "Vizela", "Vila Nova de Famalicão", "Felgueiras"}},
        {"Póvoa de Lanhoso", {"Amares", "Braga", "Fafe", "Guimarães", "Vieira do Minho"}},
        {"Terras de Bouro", {"Amares", "Vieira do Minho", "Vila Verde"}},
        {"Vieira do Minho", {"Cabeceiras de Basto", "Póvoa de Lanhoso", "Terras de Bouro", "Amares", "Montalegre"}},
        {"Vila Nova de Famalicão", {"Barcelos", "Braga", "Guimarães", "Santo Tirso", "Trofa", "Vila do Conde"}},
        {"Vila Verde", {"Amares", "Braga", "Ponte da Barca", "Ponte de Lima", "Terras de Bouro"}},
        {"Vizela", {"Guimarães", "Fafe", "Felgueiras"}},

        // District of Bragança
        {"Alfândega da Fé", {"Bragança", "Macedo de Cavaleiros", "Mirandela", "Torre de Moncorvo", "Vila Flor"}},
        {"Bragança", {"Vimioso", "Alfândega da Fé", "Macedo de Cavaleiros", "Miranda do Douro", "Mogadouro", "Vinhais"}},
        {"Carrazeda de Ansiães", {"Vila Flor", "Torre de Moncorvo", "Murça", "Alijó", "São João da Pesqueira"}},
        {"Freixo de Espada à Cinta", {"Torre de Moncorvo", "Mogadouro", "Figueira de Castelo Rodrigo"}},
        {"Macedo de Cavaleiros", {"Vimioso", "Alfândega da Fé", "Bragança", "Mirandela", "Vinhais"}},
        {"Miranda do Douro", {"Bragança", "Mogadouro", "Vimioso"}},
        {"Mirandela", {"Alfândega da Fé", "Macedo de Cavaleiros", "Vinhais", "Valpaços", "Murça", "Vila Flor"}},
        {"Mogadouro", {"Vimioso", "Bragança", "Freixo de Espada à Cinta", "Miranda do Douro", "Torre de Moncorvo"}},
        {"Torre de Moncorvo", {"Carrazeda de Ansiães", "Vila Flor", "Alfândega da Fé", "Freixo de Espada à Cinta", "Mogadouro", "Vila Nova de Foz Côa"}},
        {"Vila Flor", {"Alfândega da Fé", "Carrazeda de Ansiães", "Mirandela", "Torre de Moncorvo"}},
        {"Vinhais", {"Bragança", "Macedo de Cavaleiros", "Mirandela", "Valpaços", "Chaves"}},
        {"Vimioso", {"Miranda do Douro", "Mogadouro", "Macedo de Cavaleiros", "Bragança"}},

        // District of Castelo Branco
        {"Belmonte", {"Covilhã", "Fundão", "Guarda", "Sabugal"}},
        {"Castelo Branco", {"Fundão", "Idanha-a-Nova", "Oleiros", "Proença-a-Nova", "Vila Velha de Ródão"}},
        {"Covilhã", {"Belmonte", "Fundão", "Manteigas", "Seia", "Gouveia", "Guarda"}},
        {"Fundão", {"Belmonte", "Castelo Branco", "Covilhã", "Oleiros", "Penamacor", "Idanha-a-Nova"}},
        {"Idanha-a-Nova", {"Castelo Branco", "Fundão", "Penamacor", "Vila Velha de Ródão"}},
        {"Oleiros", {"Castelo Branco", "Fundão", "Proença-a-Nova", "Sertã", "Pampilhosa da Serra"}},
        {"Penamacor", {"Fundão", "Idanha-a-Nova", "Sabugal"}},
        {"Proença-a-Nova", {"Nisa", "Castelo Branco", "Oleiros", "Sertã", "Vila Velha de Ródão"}},
        {"Sertã", {"Oleiros", "Proença-a-Nova", "Vila de Rei"}},
        {"Vila de Rei", {"Sertã", "Mação"}},
        {"Vila Velha de Ródão", {"Nisa", "Castelo Branco", "Idanha-a-Nova", "Proença-a-Nova"}},

        // District of Coimbra
        {"Arganil", {"Oliveira do Hospital", "Tábua", "Pampilhosa da Serra", "Góis", "Penacova", "Gouveia", "Seia"}},
        {"Cantanhede", {"Mealhada", "Mira", "Montemor-o-Velho", "Coimbra", "Figueira da Foz"}},
        {"Coimbra", {"Cantanhede", "Mealhada", "Penacova", "Condeixa-a-Nova", "Montemor-o-Velho"}},
        {"Condeixa-a-Nova", {"Coimbra", "Montemor-o-Velho", "Soure", "Penela"}},
        {"Figueira da Foz", {"Cantanhede", "Montemor-o-Velho", "Pombal"}},
        {"Góis", {"Arganil", "Pampilhosa da Serra", "Lousã", "Pedrógão Grande", "Vila Nova de Poiares"}},
        {"Lousã", {"Góis", "Miranda do Corvo", "Vila Nova de Poiares"}},
        {"Mira", {"Cantanhede", "Vagos"}},
        {"Miranda do Corvo", {"Lousã", "Penela", "Vila Nova de Poiares"}},
        {"Montemor-o-Velho", {"Cantanhede", "Coimbra", "Condeixa-a-Nova", "Figueira da Foz", "Soure"}},
        {"Oliveira do Hospital", {"Arganil", "Seia", "Tábua"}},
        {"Pampilhosa da Serra", {"Arganil", "Góis", "Oleiros"}},
        {"Penacova", {"Arganil", "Coimbra", "Mealhada", "Mortágua"}},
        {"Penela", {"Condeixa-a-Nova", "Miranda do Corvo", "Ansião"}},
        {"Soure", {"Montemor-o-Velho", "Pombal", "Condeixa-a-Nova", "Ansião"}},
        {"Tábua", {"Oliveira do Hospital", "Arganil", "Seia"}},
        {"Vila Nova de Poiares", {"Lousã", "Miranda do Corvo", "Góis", "Mortágua"}},

        // District of Évora
        {"Alandroal", {"Elvas", "Borba", "Reguengos de Monsaraz", "Vila Viçosa", "Mourão", "Redondo"}},
        {"Arraiolos", {"Sousel", "Estremoz", "Évora", "Montemor-o-Novo", "Vendas Novas"}},
        {"Borba", {"Monforte", "Estremoz", "Vila Viçosa", "Alandroal"}},
        {"Estremoz", {"Monforte", "Borba", "Évora", "Arraiolos", "Vila Viçosa", "Sousel", "Redondo"}},
        {"Évora", {"Estremoz", "Arraiolos", "Montemor-o-Novo", "Redondo", "Viana do Alentejo", "Reguengos de Monsaraz", "Portel"}},
        {"Montemor-o-Novo", {"Arraiolos", "Viana do Alentejo", "Évora", "Vendas Novas", "Pombal"}},
        {"Mourão", {"Reguengos de Monsaraz", "Alandroal", "Portel"}},
        {"Portel", {"Reguengos de Monsaraz", "Évora", "Mourão"}},
        {"Redondo", {"Estremoz", "Vila Viçosa", "Alandroal", "Évora"}},
        {"Reguengos de Monsaraz", {"Portel", "Mourão", "Alandroal", "Évora"}},
        {"Vendas Novas", {"Montemor-o-Novo", "Arraiolos"}},
        {"Viana do Alentejo", {"Montemor-o-Novo", "Évora", "Alvito"}},
        {"Vila Viçosa", {"Elvas", "Estremoz", "Borba", "Alandroal", "Redondo"}},
		{"Mora", {"Coruche", "Avis"}},

        // District of Faro
        {"Albufeira", {"Silves", "Loulé", "Faro"}},
        {"Alcoutim", {"Castro Marim", "Tavira", "Mértola", "Loulé"}},
        {"Aljezur", {"Vila do Bispo", "Lagos", "Odemira", "Monchique"}},
        {"Castro Marim", {"Alcoutim", "Vila Real de Santo António", "Tavira"}},
        {"Faro", {"São Brás de Alportel", "Loulé", "Albufeira", "Olhão"}},
        {"Lagoa", {"Silves", "Loulé", "Portimão"}},
        {"Lagos", {"Vila do Bispo", "Aljezur", "Portimão",  "Monchique"}},
        {"Loulé", {"Alcoutim", "Albufeira", "Silves", "Faro", "São Brás de Alportel", "Tavira", "Lagoa"}},
        {"Monchique", {"Portimão", "Silves", "Odemira", "Aljezur", "Lagos"}},
        {"Olhão", {"Faro", "Tavira"}},
        {"Portimão", {"Monchique", "Lagos", "Lagoa", "Silves"}},
        {"São Brás de Alportel", {"Faro", "Loulé", "Tavira"}},
        {"Silves", {"Albufeira", "Lagoa", "Loulé", "Monchique", "Odemira", "Portimão"}},
        {"Tavira", {"Castro Marim", "Olhão", "Loulé", "São Brás de Alportel", "Alcoutim"}},
        {"Vila do Bispo", {"Lagos", "Aljezur"}},
        {"Vila Real de Santo António", {"Castro Marim"}},

        // District of Guarda
        {"Aguiar da Beira", {"Sátão", "Penalva do Castelo", "Trancoso", "Fornos de Algodres"}},
        {"Almeida", {"Pinhel", "Figueira de Castelo Rodrigo", "Trancoso", "Guarda"}},
        {"Celorico da Beira", {"Fornos de Algodres", "Gouveia", "Guarda", "Mêda", "Trancoso", "Seia", "Amarante"}},
        {"Figueira de Castelo Rodrigo", {"Pinhel", "Almeida", "Freixo de Espada à Cinta", "Vila Nova de Foz Côa"}},
        {"Fornos de Algodres", {"Aguiar da Beira", "Gouveia", "Celorico da Beira"}},
        {"Gouveia", {"Seia", "Mangualde", "Nelas", "Oliveira do Hospital", "Celorico da Beira", "Covilhã", "Fornos de Algodres"}},
        {"Guarda", {"Celorico da Beira", "Almeida", "Pinhel", "Manteigas", "Sabugal", "Belmonte", "Covilhã"}},
        {"Manteigas", {"Guarda", "Seia", "Covilhã"}},
        {"Mêda", {"Celorico da Beira", "Trancoso", "Penedono", "Pinhel", "Vila Nova de Foz Côa"}},
        {"Pinhel", {"Almeida", "Figueira de Castelo Rodrigo", "Mêda", "Trancoso", "Guarda"}},
        {"Sabugal", {"Guarda", "Belmonte", "Penamacor"}},
        {"Seia", {"Manteigas", "Gouveia", "Oliveira do Hospital", "Arganil", "Tábua", "Nelas", "Mangualde", "Celorico da Beira", "Covilhã"}},
        {"Trancoso", {"Celorico da Beira", "Almeida", "Mêda", "Pinhel", "Aguiar da Beira", "Penedono"}},
        {"Vila Nova de Foz Côa", {"Figueira de Castelo Rodrigo", "Mêda", "Torre de Moncorvo", "Penedono"}},

        // District of Leiria
        {"Alcobaça", {"Caldas da Rainha", "Marinha Grande", "Batalha", "Porto de Mós", "Nazaré"}},
        {"Alvaiázere", {"Ansião", "Figueiró dos Vinhos", "Ferreira do Zêzere", "Ourém"}},
        {"Ansião", {"Alvaiázere", "Pombal", "Soure", "Penela", "Figueiró dos Vinhos"}},
        {"Batalha", {"Alcobaça", "Porto de Mós", "Leiria", "Marinha Grande"}},
        {"Bombarral", {"Caldas da Rainha", "Lourinhã", "Óbidos", "Cadaval"}},
        {"Caldas da Rainha", {"Bombarral", "Óbidos", "Alcobaça", "Nazaré", "Cadaval"}},
        {"Castanheira de Pêra", {"Figueiró dos Vinhos", "Pedrógão Grande"}},
        {"Figueiró dos Vinhos", {"Ansião", "Pedrógão Grande", "Castanheira de Pêra", "Ferreira do Zêzere", "Alvaiázere"}},
        {"Leiria", {"Marinha Grande", "Pombal", "Batalha", "Porto de Mós"}},
        {"Marinha Grande", {"Leiria", "Alcobaça", "Batalha"}},
        {"Nazaré", {"Caldas da Rainha", "Alcobaça"}},
        {"Óbidos", {"Bombarral", "Caldas da Rainha", "Peniche"}},
        {"Pedrógão Grande", {"Figueiró dos Vinhos", "Castanheira de Pêra", "Góis"}},
        {"Peniche", {"Óbidos"}},
        {"Pombal", {"Ansião", "Leiria", "Soure", "Montemor-o-Velho", "Figueira da Foz"}},
        {"Porto de Mós", {"Alcobaça", "Batalha", "Leiria", "Ourém"}},

        // District of Lisboa
        {"Alenquer", {"Azambuja", "Cadaval", "Arruda dos Vinhos", "Sobral de Monte Agraço"}},
        {"Amadora", {"Odivelas", "Lisboa", "Sintra"}},
        {"Arruda dos Vinhos", {"Alenquer", "Vila Franca de Xira", "Loures", "Sobral de Monte Agraço"}},
        {"Azambuja", {"Cartaxo", "Vila Franca de Xira", "Alenquer"}},
        {"Cadaval", {"Alenquer", "Caldas da Rainha", "Lourinhã", "Bombarral", "Torres Vedras"}},
        {"Cascais", {"Oeiras", "Sintra"}},
        {"Lisboa", {"Odivelas", "Loures", "Amadora", "Oeiras", "Sintra", "Almada"}},
        {"Loures", {"Mafra", "Vila Franca de Xira", "Lisboa", "Sintra", "Odivelas", "Arruda dos Vinhos"}},
        {"Lourinhã", {"Bombarral", "Cadaval", "Marinha Grande", "Torres Vedras"}},
        {"Mafra", {"Torres Vedras", "Sintra", "Loures"}},
        {"Odivelas", {"Loures", "Amadora", "Lisboa"}},
        {"Oeiras", {"Lisboa", "Cascais", "Sintra"}},
        {"Sintra", {"Cascais", "Oeiras", "Amadora", "Lisboa", "Loures", "Mafra"}},
        {"Sobral de Monte Agraço", {"Arruda dos Vinhos", "Alenquer", "Torres Vedras"}},
        {"Torres Vedras", {"Lourinhã", "Mafra", "Cadaval", "Sobral de Monte Agraço"}},
        {"Vila Franca de Xira", {"Azambuja", "Loures", "Arruda dos Vinhos"}},

        // District of Portalegre
        {"Alter do Chão", {"Fronteira", "Avis", "Ponte de Sor"}},
        {"Arronches", {"Campo Maior", "Portalegre", "Monforte"}},
        {"Avis", {"Mora", "Alter do Chão", "Ponte de Sor", "Fronteira", "Sousel"}},
        {"Campo Maior", {"Arronches", "Elvas"}},
        {"Castelo de Vide", {"Nisa", "Marvão", "Portalegre"}},
        {"Crato", {"Fronteira", "Nisa"}},
        {"Elvas", {"Campo Maior", "Monforte", "Vila Viçosa", "Alandroal"}},
        {"Fronteira", {"Alter do Chão", "Avis", "Crato", "Sousel"}},
        {"Gavião", {"Nisa", "Ponte de Sor", "Mação", "Abrantes"}},
        {"Marvão", {"Castelo de Vide", "Portalegre"}},
        {"Monforte", {"Estremoz", "Elvas", "Portalegre", "Arronches", "Borba"}},
        {"Nisa", {"Castelo de Vide", "Proença-a-Nova", "Crato", "Gavião", "Portalegre", "Mação", "Vila Velha de Ródão"}},
        {"Ponte de Sor", {"Avis", "Gavião", "Alter do Chão"}},
        {"Portalegre", {"Monforte", "Arronches", "Castelo de Vide", "Marvão", "Nisa"}},
        {"Sousel", {"Fronteira", "Avis", "Estremoz", "Arraiolos"}},

        // District of Porto
        {"Amarante", {"Baião", "Marco de Canaveses", "Celorico de Basto", "Felgueiras"}},
        {"Baião", {"Amarante", "Cinfães", "Marco de Canaveses"}},
        {"Felgueiras", {"Guimarães", "Vizela", "Amarante", "Penafiel", "Lousada", "Celorico de Basto", "Fafe"}},
        {"Gondomar", {"Maia", "Porto", "Valongo", "Vila Nova de Gaia"}},
        {"Lousada", {"Felgueiras", "Paredes", "Penafiel", "Paços de Ferreira"}},
        {"Maia", {"Gondomar", "Matosinhos", "Porto", "Valongo", "Vila do Conde", "Trofa"}},
        {"Marco de Canaveses", {"Amarante", "Baião", "Penafiel"}},
        {"Matosinhos", {"Maia", "Porto"}},
        {"Paços de Ferreira", {"Paredes", "Santo Tirso", "Lousada"}},
        {"Paredes", {"Paços de Ferreira", "Penafiel", "Lousada", "Valongo"}},
        {"Penafiel", {"Marco de Canaveses", "Paredes", "Felgueiras", "Lousada", "Castelo de Paiva"}},
        {"Porto", {"Maia", "Matosinhos", "Gondomar", "Vila Nova de Gaia"}},
        {"Póvoa de Varzim", {"Vila do Conde", "Barcelos", "Esposende"}},
        {"Santo Tirso", {"Trofa", "Paços de Ferreira", "Guimarães", "Vila Nova de Famalicão"}},
        {"Trofa", {"Santo Tirso", "Maia", "Vila Nova de Famalicão", "Vila do Conde"}},
        {"Valongo", {"Maia", "Paredes", "Gondomar"}},
        {"Vila do Conde", {"Trofa", "Póvoa de Varzim", "Maia", "Vila Nova de Famalicão"}},
        {"Vila Nova de Gaia", {"Gondomar", "Porto", "Espinho", "Santa Maria da Feira"}},

        // District of Santarém
        {"Abrantes", {"Gavião", "Constância", "Sardoal", "Mação", "Tomar", "Ferreira do Zêzere"}},
        {"Alcanena", {"Torres Novas", "Santarém", "Ourém"}},
        {"Almeirim", {"Santarém", "Chamusca", "Cartaxo"}},
        {"Alpiarça", {"Santarém", "Chamusca"}},
        {"Benavente", {"Coruche", "Salvaterra de Magos"}},
        {"Cartaxo", {"Almeirim", "Azambuja", "Rio Maior"}},
        {"Chamusca", {"Santarém", "Almeirim", "Alpiarça", "Golegã"}},
        {"Constância", {"Abrantes", "Vila Nova da Barquinha"}},
        {"Coruche", {"Benavente", "Salvaterra de Magos", "Mora", "Montijo"}},
        {"Entroncamento", {"Vila Nova da Barquinha", "Torres Novas"}},
        {"Ferreira do Zêzere", {"Tomar", "Abrantes", "Alvaiázere", "Figueiró dos Vinhos"}},
        {"Golegã", {"Chamusca", "Torres Novas", "Santarém"}},
        {"Mação", {"Nisa", "Sardoal", "Abrantes", "Vila de Rei", "Gavião"}},
        {"Ourém", {"Torres Novas", "Tomar", "Alcanena", "Alvaiázere", "Porto de Mós"}},
        {"Rio Maior", {"Santarém", "Torres Novas", "Cartaxo"}},
        {"Santarém", {"Rio Maior", "Golegã", "Torres Novas", "Chamusca", "Almeirim", "Alpiarça", "Alcanena"}},
        {"Sardoal", {"Mação", "Abrantes"}},
        {"Tomar", {"Abrantes", "Ourém", "Ferreira do Zêzere"}},
        {"Torres Novas", {"Golegã", "Entroncamento", "Alcanena", "Ourém", "Rio Maior", "Santarém"}},
        {"Vila Nova da Barquinha", {"Constância", "Entroncamento"}},
		{"Salvaterra de Magos", {"Benavente", "Coruche"}},

        // District of Setúbal
        {"Alcácer do Sal", {"Santiago do Cacém", "Grândola"}},
        {"Alcochete", {"Montijo"}},
        {"Almada", {"Seixal", "Lisboa"}},
        {"Barreiro", {"Moita", "Seixal"}},
        {"Grândola", {"Santiago do Cacém", "Alcácer do Sal", "Odemira"}},
        {"Moita", {"Barreiro", "Montijo", "Palmela", "Setúbal"}},
        {"Montijo", {"Moita", "Palmela", "Alcochete", "Coruche"}},
        {"Palmela", {"Moita", "Setúbal", "Montijo"}},
        {"Santiago do Cacém", {"Grândola", "Alcácer do Sal", "Odemira", "Sines"}},
        {"Seixal", {"Almada", "Barreiro"}},
        {"Setúbal", {"Palmela", "Sesimbra", "Moita"}},
        {"Sesimbra", {"Setúbal"}},
		{"Sines", {"Odemira", "Santiago do Cacém"}},

        // District of Viana do Castelo
        {"Arcos de Valdevez", {"Ponte da Barca", "Ponte de Lima", "Monção"}},
        {"Caminha", {"Vila Nova de Cerveira", "Viana do Castelo"}},
        {"Melgaço", {"Monção"}},
        {"Monção", {"Melgaço", "Valença", "Arcos de Valdevez"}},
        {"Paredes de Coura", {"Valença", "Vila Nova de Cerveira"}},
        {"Ponte da Barca", {"Arcos de Valdevez", "Ponte de Lima", "Vila Verde"}},
        {"Ponte de Lima", {"Arcos de Valdevez", "Ponte da Barca", "Viana do Castelo", "Vila Verde"}},
        {"Valença", {"Monção", "Paredes de Coura", "Vila Nova de Cerveira"}},
        {"Viana do Castelo", {"Ponte de Lima", "Caminha", "Vila Nova de Cerveira", "Barcelos", "Esposende"}},
        {"Vila Nova de Cerveira", {"Valença", "Viana do Castelo", "Caminha", "Paredes de Coura"}},

        // District of Vila Real
        {"Alijó", {"Murça", "Sabrosa", "Carrazeda de Ansiães"}},
        {"Boticas", {"Chaves", "Montalegre"}},
        {"Chaves", {"Boticas", "Montalegre", "Valpaços"}},
        {"Mesão Frio", {"Peso da Régua", "Santa Marta de Penaguião"}},
        {"Mondim de Basto", {"Ribeira de Pena", "Cabeceiras de Basto", "Braga", "Celorico de Basto"}},
        {"Montalegre", {"Boticas", "Chaves", "Vieira do Minho"}},
        {"Murça", {"Alijó", "Valpaços", "Carrazeda de Ansiães", "Mirandela"}},
        {"Peso da Régua", {"Mesão Frio", "Santa Marta de Penaguião", "Vila Real", "Armamar", "Lamego"}},
        {"Ribeira de Pena", {"Mondim de Basto", "Vila Pouca de Aguiar"}},
        {"Sabrosa", {"Alijó", "Vila Real"}},
        {"Santa Marta de Penaguião", {"Peso da Régua", "Mesão Frio", "Vila Real"}},
        {"Valpaços", {"Murça", "Chaves", "Mirandela", "Vinhais"}},
        {"Vila Pouca de Aguiar", {"Ribeira de Pena", "Vila Real"}},
        {"Vila Real", {"Santa Marta de Penaguião", "Sabrosa", "Peso da Régua", "Vila Pouca de Aguiar"}},

        // District of Viseu
        {"Armamar", {"Tabuaço", "Moimenta da Beira", "Peso da Régua"}},
        {"Carregal do Sal", {"Santa Comba Dão", "Tondela"}},
        {"Castro Daire", {"Vila Nova de Paiva", "Viseu", "Lamego", "São Pedro do Sul", "Cinfães", "Oliveira de Frades"}},
        {"Cinfães", {"Castro Daire", "São Pedro do Sul", "Baião", "Resende"}},
        {"Lamego", {"Castro Daire", "Peso da Régua", "Tarouca"}},
        {"Mangualde", {"Nelas", "Sátão", "Viseu", "Gouveia", "Seia", "Penalva do Castelo"}},
        {"Moimenta da Beira", {"Vila Nova de Paiva", "Armamar", "Tarouca", "Penedono", "Sernancelhe", "Tabuaço"}},
        {"Mortágua", {"Santa Comba Dão", "Vila Nova de Poiares", "Penacova", "Mealhada"}},
        {"Nelas", {"Mangualde", "Seia", "Gouveia"}},
        {"Oliveira de Frades", {"Castro Daire", "Vouzela"}},
        {"Penalva do Castelo", {"Mangualde", "Sátão"}},
        {"Penedono", {"Moimenta da Beira", "Sernancelhe", "Mêda", "São João da Pesqueira", "Vila Nova de Foz Côa", "Trancoso"}},
        {"Resende", {"Cinfães"}},
        {"Santa Comba Dão", {"Carregal do Sal", "Tondela", "Mortágua"}},
        {"São Pedro do Sul", {"Castro Daire", "Cinfães"}},
        {"Sátão", {"Vila Nova de Paiva", "Penalva do Castelo", "Mangualde", "Aguiar da Beira"}},
        {"Sernancelhe", {"Penedono", "Moimenta da Beira"}},
        {"Tabuaço", {"Moimenta da Beira", "Armamar"}},
        {"Tarouca", {"Vila Nova de Paiva", "Lamego", "Moimenta da Beira"}},
        {"Tondela", {"Carregal do Sal", "Santa Comba Dão"}},
        {"Viseu", {"Vila Nova de Paiva", "Castro Daire", "Mangualde"}},
        {"Vouzela", {"Oliveira de Frades"}},
		{"São João da Pesqueira", {"Carrazeda de Ansiães", "Penedono"}},
        {"Vila Nova de Paiva", {"Moimenta da Beira", "Tarouca", "Castro Daire", "Viseu", "Sátão"}}

    };
    /*std::map<std::string, std::vector<std::string>> neighbors = {
        {"1", {"2", "3"}},
        {"2", {"1", "4"}},
        {"3", {"1", "4"}},
        {"4", {"2", "3", "5"}},

        {"5", {"4", "6", "7"}},
        {"6", {"5"}},
        {"7", {"5", "8"}},

        {"8", {"7", "10", "9"}},
        {"9", {"8", "10"}},
        {"10", {"8", "9"}}
    };*/
    return neighbors;
}