#include <vector>
#include <string>
#include <map>
#include <GraphInfo.h>


std::vector<std::string> getListOfZones(){
    std::vector<std::string> ans = {"Aveiro", "Beja","Braga",
                                    "Bragança","Castelo Branco","Coimbra",
                                    "Évora","Faro","Guarda",
                                    "Leiria","Lisboa","Portalegre",
                                    "Porto","Santarém","Setúbal",
                                    "Viana do Castelo","Vila Real","Viseu"
                                    };
    //std::vector<std::string> ans = {"A", "B", "C"};
    return ans;
}


std::vector<std::vector<std::string>> getListOfVertices(){
    std::vector<std::vector<std::string>> ans = {{"Águeda", "75810", "Aveiro"},
                                                {"Albergaria-a-Velha", "25380", "Aveiro"},
                                                {"Anadia", "13770", "Aveiro"},
                                                {"Arouca", "47460", "Aveiro"},
                                                {"Aveiro", "55890", "Aveiro"},
                                                {"Castelo de Paiva", "12980", "Aveiro"},
                                                {"Espinho", "30870", "Aveiro"},
                                                {"Estarreja", "27340", "Aveiro"},
                                                {"Ílhavo", "37890", "Aveiro"},
                                                {"Mealhada", "21670", "Aveiro"},
                                                {"Murtosa", "13940", "Aveiro"},
                                                {"Oliveira de Azeméis", "45230", "Aveiro"},
                                                {"Oliveira do Bairro", "24180", "Aveiro"},
                                                {"Ovar", "55210", "Aveiro"},
                                                {"Santa Maria da Feira", "57480", "Aveiro"},
                                                {"São João da Madeira", "22170", "Aveiro"},
                                                {"Sever do Vouga", "12280", "Aveiro"},
                                                {"Vagos", "22060", "Aveiro"},
                                                {"Vale de Cambra", "23040", "Aveiro"},

                                                {"Aljustrel", "15640", "Beja"},
                                                {"Almodôvar", "7260", "Beja"},
                                                {"Alvito", "2590", "Beja"},
                                                {"Barrancos", "1710", "Beja"},
                                                {"Beja", "35620", "Beja"},
                                                {"Castro Verde", "7270", "Beja"},
                                                {"Cuba", "4730", "Beja"},
                                                {"Ferreira do Alentejo", "8100", "Beja"},
                                                {"Mértola", "6430", "Beja"},
                                                {"Moura", "14980", "Beja"},
                                                {"Odemira", "26190", "Beja"},
                                                {"Ourique", "6000", "Beja"},
                                                {"Serpa", "15020", "Beja"},
                                                {"Vidigueira", "5700", "Beja"},

                                                {"Amares", "18430", "Braga"},
                                                {"Barcelos", "124500", "Braga"},
                                                {"Braga", "192500", "Braga"},
                                                {"Cabeceiras de Basto", "16630", "Braga"},
                                                {"Celorico de Basto", "19860", "Braga"},
                                                {"Esposende", "34580", "Braga"},
                                                {"Fafe", "50650", "Braga"},
                                                {"Guimarães", "158120", "Braga"},
                                                {"Póvoa de Lanhoso", "22210", "Braga"},
                                                {"Terras de Bouro", "7690", "Braga"},
                                                {"Vieira do Minho", "12300", "Braga"},
                                                {"Vila Nova de Famalicão", "134570", "Braga"},
                                                {"Vila Verde", "49180", "Braga"},
                                                {"Vizela", "23940", "Braga"},

                                                {"Alfândega da Fé", "5070", "Bragança"},
                                                {"Bragança", "35160", "Bragança"},
                                                {"Carrazeda de Ansiães", "5950", "Bragança"},
                                                {"Freixo de Espada à Cinta", "3640", "Bragança"},
                                                {"Macedo de Cavaleiros", "15550", "Bragança"},
                                                {"Miranda do Douro", "7400", "Bragança"},
                                                {"Mirandela", "23820", "Bragança"},
                                                {"Mogadouro", "9370", "Bragança"},
                                                {"Torre de Moncorvo", "8220", "Bragança"},
                                                {"Vila Flor", "6710", "Bragança"},
                                                {"Vimioso", "4210", "Bragança"},
                                                {"Vinhais", "7700", "Bragança"},

                                                {"Belmonte", "6580", "Castelo Branco"},
                                                {"Castelo Branco", "55450", "Castelo Branco"},
                                                {"Covilhã", "51020", "Castelo Branco"},
                                                {"Fundão", "29760", "Castelo Branco"},
                                                {"Idanha-a-Nova", "9210", "Castelo Branco"},
                                                {"Oleiros", "5440", "Castelo Branco"},
                                                {"Penamacor", "5220", "Castelo Branco"},
                                                {"Proença-a-Nova", "8390", "Castelo Branco"},
                                                {"Sertã", "15240", "Castelo Branco"},
                                                {"Vila de Rei", "3250", "Castelo Branco"},
                                                {"Vila Velha de Ródão", "3520", "Castelo Branco"},

                                                {"Arganil", "12340", "Coimbra"},
                                                {"Cantanhede", "36850", "Coimbra"},
                                                {"Coimbra", "143380", "Coimbra"},
                                                {"Condeixa-a-Nova", "17590", "Coimbra"},
                                                {"Figueira da Foz", "62190", "Coimbra"},
                                                {"Góis", "3880", "Coimbra"},
                                                {"Lousã", "17720", "Coimbra"},
                                                {"Mira", "12760", "Coimbra"},
                                                {"Miranda do Corvo", "13560", "Coimbra"},
                                                {"Montemor-o-Velho", "26170", "Coimbra"},
                                                {"Oliveira do Hospital", "20370", "Coimbra"},
                                                {"Pampilhosa da Serra", "4420", "Coimbra"},
                                                {"Penacova", "15510", "Coimbra"},
                                                {"Penela", "6290", "Coimbra"},
                                                {"Soure", "19780", "Coimbra"},
                                                {"Tábua", "12270", "Coimbra"},
                                                {"Vila Nova de Poiares", "7430", "Coimbra"},

                                                {"Alandroal", "5700", "Évora"},
                                                {"Arraiolos", "7300", "Évora"},
                                                {"Borba", "7300", "Évora"},
                                                {"Estremoz", "14400", "Évora"},
                                                {"Évora", "56800", "Évora"},
                                                {"Montemor-o-Novo", "17540", "Évora"},
                                                {"Mora", "4850", "Évora"},
                                                {"Mourão", "2600", "Évora"},
                                                {"Portel", "5950", "Évora"},
                                                {"Redondo", "6300", "Évora"},
                                                {"Reguengos de Monsaraz", "10990", "Évora"},
                                                {"Vendas Novas", "11940", "Évora"},
                                                {"Viana do Alentejo", "5900", "Évora"},
                                                {"Vila Viçosa", "8800", "Évora"},

                                                {"Albufeira", "44150", "Faro"},
                                                {"Alcoutim", "2600", "Faro"},
                                                {"Aljezur", "6100", "Faro"},
                                                {"Castro Marim", "6700", "Faro"},
                                                {"Faro", "61830", "Faro"},
                                                {"Lagoa", "22820", "Faro"},
                                                {"Lagos", "31690", "Faro"},
                                                {"Loulé", "70790", "Faro"},
                                                {"Monchique", "5900", "Faro"},
                                                {"Olhão", "45800", "Faro"},
                                                {"Portimão", "55160", "Faro"},
                                                {"São Brás de Alportel", "10950", "Faro"},
                                                {"Silves", "37600", "Faro"},
                                                {"Tavira", "26970", "Faro"},
                                                {"Vila do Bispo", "5500", "Faro"},
                                                {"Vila Real de Santo António", "19030", "Faro"},

                                                {"Aguiar da Beira", "5480", "Guarda"},
                                                {"Almeida", "7260", "Guarda"},
                                                {"Celorico da Beira", "7900", "Guarda"},
                                                {"Figueira de Castelo Rodrigo", "6420", "Guarda"},
                                                {"Fornos de Algodres", "4700", "Guarda"},
                                                {"Gouveia", "13760", "Guarda"},
                                                {"Guarda", "42680", "Guarda"},
                                                {"Manteigas", "3200", "Guarda"},
                                                {"Mêda", "5100", "Guarda"},
                                                {"Pinhel", "9400", "Guarda"},
                                                {"Sabugal", "12530", "Guarda"},
                                                {"Seia", "24300", "Guarda"},
                                                {"Trancoso", "9150", "Guarda"},
                                                {"Vila Nova de Foz Côa", "7400", "Guarda"},

                                                {"Alcobaça", "56100", "Leiria"},
                                                {"Alvaiázere", "6800", "Leiria"},
                                                {"Ansião", "13140", "Leiria"},
                                                {"Batalha", "15580", "Leiria"},
                                                {"Bombarral", "13120", "Leiria"},
                                                {"Caldas da Rainha", "51700", "Leiria"},
                                                {"Castanheira de Pêra", "3100", "Leiria"},
                                                {"Figueiró dos Vinhos", "6600", "Leiria"},
                                                {"Leiria", "128300", "Leiria"},
                                                {"Marinha Grande", "39200", "Leiria"},
                                                {"Nazaré", "15200", "Leiria"},
                                                {"Óbidos", "11690", "Leiria"},
                                                {"Pedrógão Grande", "3200", "Leiria"},
                                                {"Peniche", "27650", "Leiria"},
                                                {"Pombal", "55900", "Leiria"},
                                                {"Porto de Mós", "24700", "Leiria"},

                                                {"Alenquer", "43400", "Lisboa"},
                                                {"Amadora", "175500", "Lisboa"},
                                                {"Arruda dos Vinhos", "13300", "Lisboa"},
                                                {"Azambuja", "21300", "Lisboa"},
                                                {"Cadaval", "14500", "Lisboa"},
                                                {"Cascais", "214200", "Lisboa"},
                                                {"Lisboa", "506700", "Lisboa"},
                                                {"Loures", "207800", "Lisboa"},
                                                {"Lourinhã", "25700", "Lisboa"},
                                                {"Mafra", "86800", "Lisboa"},
                                                {"Odivelas", "145700", "Lisboa"},
                                                {"Oeiras", "174300", "Lisboa"},
                                                {"Sintra", "385000", "Lisboa"},
                                                {"Sobral de Monte Agraço", "10400", "Lisboa"},
                                                {"Torres Vedras", "81900", "Lisboa"},
                                                {"Vila Franca de Xira", "137000", "Lisboa"},

                                                {"Alter do Chão", "3700", "Portalegre"},
                                                {"Arronches", "3150", "Portalegre"},
                                                {"Avis", "4600", "Portalegre"},
                                                {"Campo Maior", "8100", "Portalegre"},
                                                {"Castelo de Vide", "3400", "Portalegre"},
                                                {"Crato", "3500", "Portalegre"},
                                                {"Elvas", "23500", "Portalegre"},
                                                {"Fronteira", "3400", "Portalegre"},
                                                {"Gavião", "4100", "Portalegre"},
                                                {"Marvão", "3000", "Portalegre"},
                                                {"Monforte", "3200", "Portalegre"},
                                                {"Nisa", "7200", "Portalegre"},
                                                {"Ponte de Sor", "16400", "Portalegre"},
                                                {"Portalegre", "15300", "Portalegre"},
                                                {"Sousel", "4500", "Portalegre"},

                                              {"Amarante", "56500", "Porto"},
                                                {"Baião", "19300", "Porto"},
                                                {"Felgueiras", "58200", "Porto"},
                                                {"Gondomar", "168500", "Porto"},
                                                {"Lousada", "47300", "Porto"},
                                                {"Maia", "135300", "Porto"},
                                                {"Marco de Canaveses", "53200", "Porto"},
                                                {"Matosinhos", "175200", "Porto"},
                                                {"Paços de Ferreira", "56400", "Porto"},
                                                {"Paredes", "86300", "Porto"},
                                                {"Penafiel", "71900", "Porto"},
                                                {"Porto", "214500", "Porto"},
                                                {"Póvoa de Varzim", "63600", "Porto"},
                                                {"Santo Tirso", "71100", "Porto"},
                                                {"Trofa", "38500", "Porto"},
                                                {"Valongo", "94400", "Porto"},
                                                {"Vila do Conde", "79600", "Porto"},
                                                {"Vila Nova de Gaia", "300500", "Porto"},

                                                {"Abrantes", "39000", "Santarém"},
                                                {"Alcanena", "13100", "Santarém"},
                                                {"Almeirim", "23300", "Santarém"},
                                                {"Alpiarça", "7900", "Santarém"},
                                                {"Benavente", "29600", "Santarém"},
                                                {"Cartaxo", "24600", "Santarém"},
                                                {"Chamusca", "10000", "Santarém"},
                                                {"Constância", "4000", "Santarém"},
                                                {"Coruche", "17000", "Santarém"},
                                                {"Entroncamento", "20500", "Santarém"},
                                                {"Ferreira do Zêzere", "8500", "Santarém"},
                                                {"Golegã", "5500", "Santarém"},
                                                {"Mação", "6800", "Santarém"},
                                                {"Ourém", "45900", "Santarém"},
                                                {"Rio Maior", "21300", "Santarém"},
                                                {"Salvaterra de Magos", "22400", "Santarém"},
                                                {"Santarém", "61100", "Santarém"},
                                                {"Sardoal", "3700", "Santarém"},
                                                {"Tomar", "40400", "Santarém"},
                                                {"Torres Novas", "36100", "Santarém"},
                                                {"Vila Nova da Barquinha", "7400", "Santarém"},

                                                {"Alcácer do Sal", "13500", "Setúbal"},
                                                {"Alcochete", "20000", "Setúbal"},
                                                {"Almada", "174000", "Setúbal"},
                                                {"Barreiro", "78000", "Setúbal"},
                                                {"Grândola", "14300", "Setúbal"},
                                                {"Moita", "66700", "Setúbal"},
                                                {"Montijo", "52600", "Setúbal"},
                                                {"Palmela", "68400", "Setúbal"},
                                                {"Santiago do Cacém", "29500", "Setúbal"},
                                                {"Seixal", "170000", "Setúbal"},
                                                {"Sesimbra", "49000", "Setúbal"},
                                                {"Setúbal", "121000", "Setúbal"},
                                                {"Sines", "14300", "Setúbal"},

                                                {"Arcos de Valdevez", "22500", "Viana do Castelo"},
                                                {"Caminha", "17000", "Viana do Castelo"},
                                                {"Melgaço", "9700", "Viana do Castelo"},
                                                {"Monção", "17500", "Viana do Castelo"},
                                                {"Paredes de Coura", "9100", "Viana do Castelo"},
                                                {"Ponte da Barca", "12000", "Viana do Castelo"},
                                                {"Ponte de Lima", "43800", "Viana do Castelo"},
                                                {"Valença", "14000", "Viana do Castelo"},
                                                {"Viana do Castelo", "88200", "Viana do Castelo"},
                                                {"Vila Nova de Cerveira", "9200", "Viana do Castelo"},

                                                {"Alijó", "11300", "Vila Real"},
                                                {"Boticas", "5100", "Vila Real"},
                                                {"Chaves", "41000", "Vila Real"},
                                                {"Mesão Frio", "4300", "Vila Real"},
                                                {"Mondim de Basto", "7500", "Vila Real"},
                                                {"Montalegre", "10600", "Vila Real"},
                                                {"Murça", "6000", "Vila Real"},
                                                {"Peso da Régua", "16800", "Vila Real"},
                                                {"Ribeira de Pena", "6500", "Vila Real"},
                                                {"Sabrosa", "6200", "Vila Real"},
                                                {"Santa Marta de Penaguião", "7400", "Vila Real"},
                                                {"Valpaços", "15700", "Vila Real"},
                                                {"Vila Pouca de Aguiar", "13300", "Vila Real"},
                                                {"Vila Real", "51500", "Vila Real"},

                                                {"Armamar", "6200", "Viseu"},
                                                {"Carregal do Sal", "9800", "Viseu"},
                                                {"Castro Daire", "15500", "Viseu"},
                                                {"Cinfães", "20100", "Viseu"},
                                                {"Lamego", "26500", "Viseu"},
                                                {"Mangualde", "19400", "Viseu"},
                                                {"Moimenta da Beira", "9800", "Viseu"},
                                                {"Mortágua", "9600", "Viseu"},
                                                {"Nelas", "14900", "Viseu"},
                                                {"Oliveira de Frades", "10200", "Viseu"},
                                                {"Penalva do Castelo", "7400", "Viseu"},
                                                {"Penedono", "3200", "Viseu"},
                                                {"Resende", "11400", "Viseu"},
                                                {"Santa Comba Dão", "11700", "Viseu"},
                                                {"São João da Pesqueira", "7600", "Viseu"},
                                                {"São Pedro do Sul", "16900", "Viseu"},
                                                {"Sátão", "12200", "Viseu"},
                                                {"Sernancelhe", "5900", "Viseu"},
                                                {"Tabuaço", "6200", "Viseu"},
                                                {"Tarouca", "8100", "Viseu"},
                                                {"Tondela", "28800", "Viseu"},
                                                {"Vila Nova de Paiva", "5500", "Viseu"},
                                                {"Viseu", "99400", "Viseu"},
                                                {"Vouzela", "10500", "Viseu"}
                                            };
    /*std::vector<std::vector<std::string>> ans = {
                                                // weight = 31
                                                {"1", "10", "A" },
                                                {"2", "5", "A" },
                                                {"3", "15", "A" },
                                                {"4", "1", "A" },
                                                // weight = 21
                                                {"5", "8", "B" },
                                                {"6", "7", "B" },
                                                {"7", "6", "B" },
                                                // weight = 9
                                                {"8", "2", "C" },
                                                {"9", "3", "C" },
                                                {"10", "4", "C" },
    };*/
    return ans;
}


std::map<std::string, std::vector<std::string>> mapOfNeigh(){
    std::map<std::string, std::vector<std::string>> neighbors = {
        // District of Aveiro
        {"Águeda", {"Anadia", "Aveiro", "Oliveira do Bairro", "Oliveira de Azeméis", "Sever do Vouga"}},
        {"Albergaria-a-Velha", {"Aveiro", "Estarreja", "Sever do Vouga", "Oliveira de Azeméis"}},
        {"Anadia", {"Águeda", "Mealhada", "Oliveira do Bairro"}},
        {"Arouca", {"Castelo de Paiva", "Oliveira de Azeméis", "Santa Maria da Feira", "Vale de Cambra"}},
        {"Aveiro", {"Águeda", "Albergaria-a-Velha", "Ílhavo", "Murtosa", "Oliveira do Bairro", "Estarreja", "Vagos"}},
        {"Castelo de Paiva", {"Arouca", "Santa Maria da Feira", "Penafiel"}},
        {"Espinho", {"Santa Maria da Feira", "Vila Nova de Gaia"}},
        {"Estarreja", {"Albergaria-a-Velha", "Aveiro", "Murtosa", "Ovar"}},
        {"Ílhavo", {"Aveiro", "Vagos"}},
        {"Mealhada", {"Anadia", "Cantanhede", "Coimbra", "Mortágua", "Penacova"}},
        {"Murtosa", {"Aveiro", "Estarreja", "Ovar"}},
        {"Oliveira de Azeméis", {"Águeda", "Albergaria-a-Velha", "Arouca", "Santa Maria da Feira", "Vale de Cambra", "Sever do Vouga", "São João da Madeira"}},
        {"Oliveira do Bairro", {"Águeda", "Anadia", "Aveiro"}},
        {"Ovar", {"Estarreja", "Murtosa", "Santa Maria da Feira"}},
        {"Santa Maria da Feira", {"Arouca", "Espinho", "Oliveira de Azeméis", "Ovar", "Vila Nova de Gaia", "Castelo de Paiva", "São João da Madeira", "Vale de Cambra"}},
        {"São João da Madeira", {"Santa Maria da Feira", "Oliveira de Azeméis"}},
        {"Sever do Vouga", {"Águeda", "Albergaria-a-Velha", "Oliveira de Azeméis", "Vale de Cambra"}},
        {"Vagos", {"Ílhavo", "Aveiro", "Mira"}},
        {"Vale de Cambra", {"Arouca", "Oliveira de Azeméis", "Santa Maria da Feira", "Sever do Vouga"}},

        // District of Beja
        {"Aljustrel", {"Almodôvar", "Castro Verde", "Ourique", "Beja", "Ferreira do Alentejo"}},
        {"Almodôvar", {"Aljustrel", "Castro Verde", "Ourique", "Odemira", "Mértola"}},
        {"Alvito", {"Beja", "Ferreira do Alentejo", "Cuba", "Viana do Alentejo"}},
        {"Barrancos", {"Moura", "Mértola"}},
        {"Beja", {"Aljustrel", "Alvito", "Cuba", "Ferreira do Alentejo", "Mértola", "Serpa", "Vidigueira"}},
        {"Castro Verde", {"Aljustrel", "Almodôvar", "Ourique", "Mértola"}},
        {"Cuba", {"Beja", "Vidigueira", "Alvito", "Ferreira do Alentejo"}},
        {"Ferreira do Alentejo", {"Beja", "Aljustrel", "Alvito", "Cuba"}},
        {"Mértola", {"Beja", "Castro Verde", "Almodôvar", "Odemira", "Serpa", "Barrancos", "Alcoutim"}},
        {"Moura", {"Barrancos", "Serpa", "Vidigueira"}},
        {"Odemira", {"Almodôvar", "Ourique", "Santiago do Cacém", "Sines", "Grândola", "Mértola", "Aljezur", "Monchique", "Silves"}},
        {"Ourique", {"Aljustrel", "Almodôvar", "Castro Verde", "Odemira"}},
        {"Serpa", {"Beja", "Moura", "Mértola"}},
        {"Vidigueira", {"Beja", "Cuba", "Moura"}},

        // District of Braga
        {"Amares", {"Braga", "Póvoa de Lanhoso", "Terras de Bouro", "Vila Verde", "Vieira do Minho"}},
        {"Barcelos", {"Braga", "Esposende", "Póvoa de Varzim", "Vila Nova de Famalicão", "Viana do Castelo"}},
        {"Braga", {"Amares", "Barcelos", "Póvoa de Lanhoso", "Vila Nova de Famalicão", "Vila Verde", "Guimarães", "Mondim de Basto"}},
        {"Cabeceiras de Basto", {"Celorico de Basto", "Fafe", "Mondim de Basto", "Vieira do Minho"}},
        {"Celorico de Basto", {"Amarante", "Felgueiras", "Fafe", "Mondim de Basto", "Cabeceiras de Basto"}},
        {"Esposende", {"Barcelos", "Póvoa de Varzim", "Viana do Castelo"}},
        {"Fafe", {"Cabeceiras de Basto", "Celorico de Basto", "Felgueiras", "Guimarães", "Póvoa de Lanhoso", "Vizela"}},
        {"Guimarães", {"Braga", "Fafe", "Póvoa de Lanhoso", "Santo Tirso", "Vizela", "Vila Nova de Famalicão", "Felgueiras"}},
        {"Póvoa de Lanhoso", {"Amares", "Braga", "Fafe", "Guimarães", "Vieira do Minho"}},
        {"Terras de Bouro", {"Amares", "Vieira do Minho", "Vila Verde"}},
        {"Vieira do Minho", {"Cabeceiras de Basto", "Póvoa de Lanhoso", "Terras de Bouro", "Amares", "Montalegre"}},
        {"Vila Nova de Famalicão", {"Barcelos", "Braga", "Guimarães", "Santo Tirso", "Trofa", "Vila do Conde"}},
        {"Vila Verde", {"Amares", "Braga", "Ponte da Barca", "Ponte de Lima", "Terras de Bouro"}},
        {"Vizela", {"Guimarães", "Fafe", "Felgueiras"}},

        // District of Bragança
        {"Alfândega da Fé", {"Bragança", "Macedo de Cavaleiros", "Mirandela", "Torre de Moncorvo", "Vila Flor"}},
        {"Bragança", {"Vimioso", "Alfândega da Fé", "Macedo de Cavaleiros", "Miranda do Douro", "Mogadouro", "Vinhais"}},
        {"Carrazeda de Ansiães", {"Vila Flor", "Torre de Moncorvo", "Murça", "Alijó", "São João da Pesqueira"}},
        {"Freixo de Espada à Cinta", {"Torre de Moncorvo", "Mogadouro", "Figueira de Castelo Rodrigo"}},
        {"Macedo de Cavaleiros", {"Vimioso", "Alfândega da Fé", "Bragança", "Mirandela", "Vinhais"}},
        {"Miranda do Douro", {"Bragança", "Mogadouro", "Vimioso"}},
        {"Mirandela", {"Alfândega da Fé", "Macedo de Cavaleiros", "Vinhais", "Valpaços", "Murça", "Vila Flor"}},
        {"Mogadouro", {"Vimioso", "Bragança", "Freixo de Espada à Cinta", "Miranda do Douro", "Torre de Moncorvo"}},
        {"Torre de Moncorvo", {"Carrazeda de Ansiães", "Vila Flor", "Alfândega da Fé", "Freixo de Espada à Cinta", "Mogadouro", "Vila Nova de Foz Côa"}},
        {"Vila Flor", {"Alfândega da Fé", "Carrazeda de Ansiães", "Mirandela", "Torre de Moncorvo"}},
        {"Vinhais", {"Bragança", "Macedo de Cavaleiros", "Mirandela", "Valpaços", "Chaves"}},
        {"Vimioso", {"Miranda do Douro", "Mogadouro", "Macedo de Cavaleiros", "Bragança"}},

        // District of Castelo Branco
        {"Belmonte", {"Covilhã", "Fundão", "Guarda", "Sabugal"}},
        {"Castelo Branco", {"Fundão", "Idanha-a-Nova", "Oleiros", "Proença-a-Nova", "Vila Velha de Ródão"}},
        {"Covilhã", {"Belmonte", "Fundão", "Manteigas", "Seia", "Gouveia", "Guarda"}},
        {"Fundão", {"Belmonte", "Castelo Branco", "Covilhã", "Oleiros", "Penamacor", "Idanha-a-Nova"}},
        {"Idanha-a-Nova", {"Castelo Branco", "Fundão", "Penamacor", "Vila Velha de Ródão"}},
        {"Oleiros", {"Castelo Branco", "Fundão", "Proença-a-Nova", "Sertã", "Pampilhosa da Serra"}},
        {"Penamacor", {"Fundão", "Idanha-a-Nova", "Sabugal"}},
        {"Proença-a-Nova", {"Nisa", "Castelo Branco", "Oleiros", "Sertã", "Vila Velha de Ródão"}},
        {"Sertã", {"Oleiros", "Proença-a-Nova", "Vila de Rei"}},
        {"Vila de Rei", {"Sertã", "Mação"}},
        {"Vila Velha de Ródão", {"Nisa", "Castelo Branco", "Idanha-a-Nova", "Proença-a-Nova"}},

        // District of Coimbra
        {"Arganil", {"Oliveira do Hospital", "Tábua", "Pampilhosa da Serra", "Góis", "Penacova", "Gouveia", "Seia"}},
        {"Cantanhede", {"Mealhada", "Mira", "Montemor-o-Velho", "Coimbra", "Figueira da Foz"}},
        {"Coimbra", {"Cantanhede", "Mealhada", "Penacova", "Condeixa-a-Nova", "Montemor-o-Velho"}},
        {"Condeixa-a-Nova", {"Coimbra", "Montemor-o-Velho", "Soure", "Penela"}},
        {"Figueira da Foz", {"Cantanhede", "Montemor-o-Velho", "Pombal"}},
        {"Góis", {"Arganil", "Pampilhosa da Serra", "Lousã", "Pedrógão Grande", "Vila Nova de Poiares"}},
        {"Lousã", {"Góis", "Miranda do Corvo", "Vila Nova de Poiares"}},
        {"Mira", {"Cantanhede", "Vagos"}},
        {"Miranda do Corvo", {"Lousã", "Penela", "Vila Nova de Poiares"}},
        {"Montemor-o-Velho", {"Cantanhede", "Coimbra", "Condeixa-a-Nova", "Figueira da Foz", "Soure"}},
        {"Oliveira do Hospital", {"Arganil", "Seia", "Tábua"}},
        {"Pampilhosa da Serra", {"Arganil", "Góis", "Oleiros"}},
        {"Penacova", {"Arganil", "Coimbra", "Mealhada", "Mortágua"}},
        {"Penela", {"Condeixa-a-Nova", "Miranda do Corvo", "Ansião"}},
        {"Soure", {"Montemor-o-Velho", "Pombal", "Condeixa-a-Nova", "Ansião"}},
        {"Tábua", {"Oliveira do Hospital", "Arganil", "Seia"}},
        {"Vila Nova de Poiares", {"Lousã", "Miranda do Corvo", "Góis", "Mortágua"}},

        // District of Évora
        {"Alandroal", {"Elvas", "Borba", "Reguengos de Monsaraz", "Vila Viçosa", "Mourão", "Redondo"}},
        {"Arraiolos", {"Sousel", "Estremoz", "Évora", "Montemor-o-Novo", "Vendas Novas"}},
        {"Borba", {"Monforte", "Estremoz", "Vila Viçosa", "Alandroal"}},
        {"Estremoz", {"Monforte", "Borba", "Évora", "Arraiolos", "Vila Viçosa", "Sousel", "Redondo"}},
        {"Évora", {"Estremoz", "Arraiolos", "Montemor-o-Novo", "Redondo", "Viana do Alentejo", "Reguengos de Monsaraz", "Portel"}},
        {"Montemor-o-Novo", {"Arraiolos", "Viana do Alentejo", "Évora", "Vendas Novas", "Pombal"}},
        {"Mourão", {"Reguengos de Monsaraz", "Alandroal", "Portel"}},
        {"Portel", {"Reguengos de Monsaraz", "Évora", "Mourão"}},
        {"Redondo", {"Estremoz", "Vila Viçosa", "Alandroal", "Évora"}},
        {"Reguengos de Monsaraz", {"Portel", "Mourão", "Alandroal", "Évora"}},
        {"Vendas Novas", {"Montemor-o-Novo", "Arraiolos"}},
        {"Viana do Alentejo", {"Montemor-o-Novo", "Évora", "Alvito"}},
        {"Vila Viçosa", {"Elvas", "Estremoz", "Borba", "Alandroal", "Redondo"}},
		{"Mora", {"Coruche", "Avis"}},

        // District of Faro
        {"Albufeira", {"Silves", "Loulé", "Faro"}},
        {"Alcoutim", {"Castro Marim", "Tavira", "Mértola", "Loulé"}},
        {"Aljezur", {"Vila do Bispo", "Lagos", "Odemira", "Monchique"}},
        {"Castro Marim", {"Alcoutim", "Vila Real de Santo António", "Tavira"}},
        {"Faro", {"São Brás de Alportel", "Loulé", "Albufeira", "Olhão"}},
        {"Lagoa", {"Silves", "Loulé", "Portimão"}},
        {"Lagos", {"Vila do Bispo", "Aljezur", "Portimão",  "Monchique"}},
        {"Loulé", {"Alcoutim", "Albufeira", "Silves", "Faro", "São Brás de Alportel", "Tavira", "Lagoa"}},
        {"Monchique", {"Portimão", "Silves", "Odemira", "Aljezur", "Lagos"}},
        {"Olhão", {"Faro", "Tavira"}},
        {"Portimão", {"Monchique", "Lagos", "Lagoa", "Silves"}},
        {"São Brás de Alportel", {"Faro", "Loulé", "Tavira"}},
        {"Silves", {"Albufeira", "Lagoa", "Loulé", "Monchique", "Odemira", "Portimão"}},
        {"Tavira", {"Castro Marim", "Olhão", "Loulé", "São Brás de Alportel", "Alcoutim"}},
        {"Vila do Bispo", {"Lagos", "Aljezur"}},
        {"Vila Real de Santo António", {"Castro Marim"}},

        // District of Guarda
        {"Aguiar da Beira", {"Sátão", "Penalva do Castelo", "Trancoso", "Fornos de Algodres"}},
        {"Almeida", {"Pinhel", "Figueira de Castelo Rodrigo", "Trancoso", "Guarda"}},
        {"Celorico da Beira", {"Fornos de Algodres", "Gouveia", "Guarda", "Mêda", "Trancoso", "Seia", "Amarante"}},
        {"Figueira de Castelo Rodrigo", {"Pinhel", "Almeida", "Freixo de Espada à Cinta", "Vila Nova de Foz Côa"}},
        {"Fornos de Algodres", {"Aguiar da Beira", "Gouveia", "Celorico da Beira"}},
        {"Gouveia", {"Seia", "Mangualde", "Nelas", "Oliveira do Hospital", "Celorico da Beira", "Covilhã", "Fornos de Algodres"}},
        {"Guarda", {"Celorico da Beira", "Almeida", "Pinhel", "Manteigas", "Sabugal", "Belmonte", "Covilhã"}},
        {"Manteigas", {"Guarda", "Seia", "Covilhã"}},
        {"Mêda", {"Celorico da Beira", "Trancoso", "Penedono", "Pinhel", "Vila Nova de Foz Côa"}},
        {"Pinhel", {"Almeida", "Figueira de Castelo Rodrigo", "Mêda", "Trancoso", "Guarda"}},
        {"Sabugal", {"Guarda", "Belmonte", "Penamacor"}},
        {"Seia", {"Manteigas", "Gouveia", "Oliveira do Hospital", "Arganil", "Tábua", "Nelas", "Mangualde", "Celorico da Beira", "Covilhã"}},
        {"Trancoso", {"Celorico da Beira", "Almeida", "Mêda", "Pinhel", "Aguiar da Beira"}},
        {"Vila Nova de Foz Côa", {"Figueira de Castelo Rodrigo", "Mêda", "Torre de Moncorvo"}},

        // District of Leiria
        {"Alcobaça", {"Caldas da Rainha", "Marinha Grande", "Batalha", "Porto de Mós", "Nazaré"}},
        {"Alvaiázere", {"Ansião", "Figueiró dos Vinhos", "Ferreira do Zêzere", "Ourém"}},
        {"Ansião", {"Alvaiázere", "Pombal", "Soure", "Penela", "Figueiró dos Vinhos"}},
        {"Batalha", {"Alcobaça", "Porto de Mós", "Leiria", "Marinha Grande"}},
        {"Bombarral", {"Caldas da Rainha", "Lourinhã", "Óbidos", "Cadaval"}},
        {"Caldas da Rainha", {"Bombarral", "Óbidos", "Alcobaça", "Nazaré", "Cadaval"}},
        {"Castanheira de Pêra", {"Figueiró dos Vinhos", "Pedrógão Grande"}},
        {"Figueiró dos Vinhos", {"Ansião", "Pedrógão Grande", "Castanheira de Pêra", "Ferreira do Zêzere", "Alvaiázere"}},
        {"Leiria", {"Marinha Grande", "Pombal", "Batalha", "Porto de Mós"}},
        {"Marinha Grande", {"Leiria", "Alcobaça", "Batalha"}},
        {"Nazaré", {"Caldas da Rainha", "Alcobaça"}},
        {"Óbidos", {"Bombarral", "Caldas da Rainha", "Peniche"}},
        {"Pedrógão Grande", {"Figueiró dos Vinhos", "Castanheira de Pêra", "Góis"}},
        {"Peniche", {"Óbidos"}},
        {"Pombal", {"Ansião", "Leiria", "Soure", "Montemor-o-Velho", "Figueira da Foz"}},
        {"Porto de Mós", {"Alcobaça", "Batalha", "Leiria", "Ourém"}},

        // District of Lisboa
        {"Alenquer", {"Azambuja", "Cadaval", "Arruda dos Vinhos", "Sobral de Monte Agraço"}},
        {"Amadora", {"Odivelas", "Lisboa", "Sintra"}},
        {"Arruda dos Vinhos", {"Alenquer", "Vila Franca de Xira", "Loures", "Sobral de Monte Agraço"}},
        {"Azambuja", {"Cartaxo", "Vila Franca de Xira", "Alenquer"}},
        {"Cadaval", {"Alenquer", "Caldas da Rainha", "Lourinhã", "Bombarral", "Torres Vedras"}},
        {"Cascais", {"Oeiras", "Sintra"}},
        {"Lisboa", {"Odivelas", "Loures", "Amadora", "Oeiras", "Sintra", "Almada"}},
        {"Loures", {"Mafra", "Vila Franca de Xira", "Lisboa", "Sintra", "Odivelas", "Arruda dos Vinhos"}},
        {"Lourinhã", {"Bombarral", "Cadaval", "Marinha Grande", "Torres Vedras"}},
        {"Mafra", {"Torres Vedras", "Sintra", "Loures"}},
        {"Odivelas", {"Loures", "Amadora", "Lisboa"}},
        {"Oeiras", {"Lisboa", "Cascais", "Sintra"}},
        {"Sintra", {"Cascais", "Oeiras", "Amadora", "Lisboa", "Loures", "Mafra"}},
        {"Sobral de Monte Agraço", {"Arruda dos Vinhos", "Alenquer", "Torres Vedras"}},
        {"Torres Vedras", {"Lourinhã", "Mafra", "Cadaval", "Sobral de Monte Agraço"}},
        {"Vila Franca de Xira", {"Azambuja", "Loures", "Arruda dos Vinhos"}},

        // District of Portalegre
        {"Alter do Chão", {"Fronteira", "Avis", "Ponte de Sor"}},
        {"Arronches", {"Campo Maior", "Portalegre", "Monforte"}},
        {"Avis", {"Mora", "Alter do Chão", "Ponte de Sor", "Fronteira", "Sousel"}},
        {"Campo Maior", {"Arronches", "Elvas"}},
        {"Castelo de Vide", {"Nisa", "Marvão", "Portalegre"}},
        {"Crato", {"Fronteira", "Nisa"}},
        {"Elvas", {"Campo Maior", "Monforte", "Vila Viçosa", "Alandroal"}},
        {"Fronteira", {"Alter do Chão", "Avis", "Crato", "Sousel"}},
        {"Gavião", {"Nisa", "Ponte de Sor", "Mação", "Abrantes"}},
        {"Marvão", {"Castelo de Vide", "Portalegre"}},
        {"Monforte", {"Estremoz", "Elvas", "Portalegre", "Arronches", "Borba"}},
        {"Nisa", {"Castelo de Vide", "Proença-a-Nova", "Crato", "Gavião", "Portalegre", "Mação", "Vila Velha de Ródão"}},
        {"Ponte de Sor", {"Avis", "Gavião", "Alter do Chão"}},
        {"Portalegre", {"Monforte", "Arronches", "Castelo de Vide", "Marvão", "Nisa"}},
        {"Sousel", {"Fronteira", "Avis", "Estremoz", "Arraiolos"}},

        // District of Porto
        {"Amarante", {"Baião", "Marco de Canaveses", "Celorico de Basto", "Felgueiras"}},
        {"Baião", {"Amarante", "Cinfães", "Marco de Canaveses"}},
        {"Felgueiras", {"Guimarães", "Vizela", "Amarante", "Penafiel", "Lousada", "Celorico de Basto", "Fafe"}},
        {"Gondomar", {"Maia", "Porto", "Valongo", "Vila Nova de Gaia"}},
        {"Lousada", {"Felgueiras", "Paredes", "Penafiel", "Paços de Ferreira"}},
        {"Maia", {"Gondomar", "Matosinhos", "Porto", "Valongo", "Vila do Conde", "Trofa"}},
        {"Marco de Canaveses", {"Amarante", "Baião", "Penafiel"}},
        {"Matosinhos", {"Maia", "Porto"}},
        {"Paços de Ferreira", {"Paredes", "Santo Tirso", "Lousada"}},
        {"Paredes", {"Paços de Ferreira", "Penafiel", "Lousada", "Valongo"}},
        {"Penafiel", {"Marco de Canaveses", "Paredes", "Felgueiras", "Lousada", "Castelo de Paiva"}},
        {"Porto", {"Maia", "Matosinhos", "Gondomar", "Vila Nova de Gaia"}},
        {"Póvoa de Varzim", {"Vila do Conde", "Barcelos", "Esposende"}},
        {"Santo Tirso", {"Trofa", "Paços de Ferreira", "Guimarães", "Vila Nova de Famalicão"}},
        {"Trofa", {"Santo Tirso", "Maia", "Vila Nova de Famalicão", "Vila do Conde"}},
        {"Valongo", {"Maia", "Paredes", "Gondomar"}},
        {"Vila do Conde", {"Trofa", "Póvoa de Varzim", "Maia", "Vila Nova de Famalicão"}},
        {"Vila Nova de Gaia", {"Gondomar", "Porto", "Espinho", "Santa Maria da Feira"}},

        // District of Santarém
        {"Abrantes", {"Gavião", "Constância", "Sardoal", "Mação", "Tomar", "Ferreira do Zêzere"}},
        {"Alcanena", {"Torres Novas", "Santarém", "Ourém"}},
        {"Almeirim", {"Santarém", "Chamusca", "Cartaxo"}},
        {"Alpiarça", {"Santarém", "Chamusca"}},
        {"Benavente", {"Coruche", "Salvaterra de Magos"}},
        {"Cartaxo", {"Almeirim", "Azambuja", "Rio Maior"}},
        {"Chamusca", {"Santarém", "Almeirim", "Alpiarça", "Golegã"}},
        {"Constância", {"Abrantes", "Vila Nova da Barquinha"}},
        {"Coruche", {"Benavente", "Salvaterra de Magos", "Mora", "Montijo"}},
        {"Entroncamento", {"Vila Nova da Barquinha", "Torres Novas"}},
        {"Ferreira do Zêzere", {"Tomar", "Abrantes", "Alvaiázere", "Figueiró dos Vinhos"}},
        {"Golegã", {"Chamusca", "Torres Novas", "Santarém"}},
        {"Mação", {"Nisa", "Sardoal", "Abrantes", "Vila de Rei", "Gavião"}},
        {"Ourém", {"Torres Novas", "Tomar", "Alcanena", "Alvaiázere", "Porto de Mós"}},
        {"Rio Maior", {"Santarém", "Torres Novas", "Cartaxo"}},
        {"Santarém", {"Rio Maior", "Golegã", "Torres Novas", "Chamusca", "Almeirim", "Alpiarça", "Alcanena"}},
        {"Sardoal", {"Mação", "Abrantes"}},
        {"Tomar", {"Abrantes", "Ourém", "Ferreira do Zêzere"}},
        {"Torres Novas", {"Golegã", "Entroncamento", "Alcanena", "Ourém", "Rio Maior", "Santarém"}},
        {"Vila Nova da Barquinha", {"Constância", "Entroncamento"}},
		{"Salvaterra de Magos", {"Benavente", "Coruche"}},

        // District of Setúbal
        {"Alcácer do Sal", {"Santiago do Cacém", "Grândola"}},
        {"Alcochete", {"Montijo"}},
        {"Almada", {"Seixal", "Lisboa"}},
        {"Barreiro", {"Moita", "Seixal"}},
        {"Grândola", {"Santiago do Cacém", "Alcácer do Sal", "Odemira"}},
        {"Moita", {"Barreiro", "Montijo", "Palmela", "Setúbal"}},
        {"Montijo", {"Moita", "Palmela", "Alcochete", "Coruche"}},
        {"Palmela", {"Moita", "Setúbal", "Montijo"}},
        {"Santiago do Cacém", {"Grândola", "Alcácer do Sal", "Odemira", "Sines"}},
        {"Seixal", {"Almada", "Barreiro"}},
        {"Setúbal", {"Palmela", "Sesimbra", "Moita"}},
        {"Sesimbra", {"Setúbal"}},
		{"Sines", {"Odemira", "Santiago do Cacém"}},

        // District of Viana do Castelo
        {"Arcos de Valdevez", {"Ponte da Barca", "Ponte de Lima", "Monção"}},
        {"Caminha", {"Vila Nova de Cerveira", "Viana do Castelo"}},
        {"Melgaço", {"Monção"}},
        {"Monção", {"Melgaço", "Valença", "Arcos de Valdevez"}},
        {"Paredes de Coura", {"Valença", "Vila Nova de Cerveira"}},
        {"Ponte da Barca", {"Arcos de Valdevez", "Ponte de Lima", "Vila Verde"}},
        {"Ponte de Lima", {"Arcos de Valdevez", "Ponte da Barca", "Viana do Castelo", "Vila Verde"}},
        {"Valença", {"Monção", "Paredes de Coura", "Vila Nova de Cerveira"}},
        {"Viana do Castelo", {"Ponte de Lima", "Caminha", "Vila Nova de Cerveira", "Barcelos", "Esposende"}},
        {"Vila Nova de Cerveira", {"Valença", "Viana do Castelo", "Caminha", "Paredes de Coura"}},

        // District of Vila Real
        {"Alijó", {"Murça", "Sabrosa", "Carrazeda de Ansiães"}},
        {"Boticas", {"Chaves", "Montalegre"}},
        {"Chaves", {"Boticas", "Montalegre", "Valpaços"}},
        {"Mesão Frio", {"Peso da Régua", "Santa Marta de Penaguião"}},
        {"Mondim de Basto", {"Ribeira de Pena", "Cabeceiras de Basto", "Braga", "Celorico de Basto"}},
        {"Montalegre", {"Boticas", "Chaves", "Vieira do Minho"}},
        {"Murça", {"Alijó", "Valpaços", "Carrazeda de Ansiães", "Mirandela"}},
        {"Peso da Régua", {"Mesão Frio", "Santa Marta de Penaguião", "Vila Real", "Armamar", "Lamego"}},
        {"Ribeira de Pena", {"Mondim de Basto", "Vila Pouca de Aguiar"}},
        {"Sabrosa", {"Alijó", "Vila Real"}},
        {"Santa Marta de Penaguião", {"Peso da Régua", "Mesão Frio", "Vila Real"}},
        {"Valpaços", {"Murça", "Chaves", "Mirandela", "Vinhais"}},
        {"Vila Pouca de Aguiar", {"Ribeira de Pena", "Vila Real"}},
        {"Vila Real", {"Santa Marta de Penaguião", "Sabrosa", "Peso da Régua", "Vila Pouca de Aguiar"}},

        // District of Viseu
        {"Armamar", {"Tabuaço", "Moimenta da Beira", "Peso da Régua"}},
        {"Carregal do Sal", {"Santa Comba Dão", "Tondela"}},
        {"Castro Daire", {"Vila Nova de Paiva", "Viseu", "Lamego", "São Pedro do Sul", "Cinfães", "Oliveira de Frades"}},
        {"Cinfães", {"Castro Daire", "São Pedro do Sul", "Baião", "Resende"}},
        {"Lamego", {"Castro Daire", "Peso da Régua", "Tarouca"}},
        {"Mangualde", {"Nelas", "Sátão", "Viseu", "Gouveia", "Seia", "Penalva do Castelo"}},
        {"Moimenta da Beira", {"Vila Nova de Paiva", "Armamar", "Tarouca", "Penedono", "Sernancelhe", "Tabuaço"}},
        {"Mortágua", {"Santa Comba Dão", "Vila Nova de Poiares", "Penacova", "Mealhada"}},
        {"Nelas", {"Mangualde", "Seia", "Gouveia"}},
        {"Oliveira de Frades", {"Castro Daire", "Vouzela"}},
        {"Penalva do Castelo", {"Mangualde", "Sátão"}},
        {"Penedono", {"Moimenta da Beira", "Sernancelhe"}},
        {"Resende", {"Cinfães"}},
        {"Santa Comba Dão", {"Carregal do Sal", "Tondela", "Mortágua"}},
        {"São Pedro do Sul", {"Castro Daire", "Cinfães"}},
        {"Sátão", {"Vila Nova de Paiva", "Penalva do Castelo", "Mangualde", "Aguiar da Beira"}},
        {"Sernancelhe", {"Penedono", "Moimenta da Beira"}},
        {"Tabuaço", {"Moimenta da Beira", "Armamar"}},
        {"Tarouca", {"Vila Nova de Paiva", "Lamego", "Moimenta da Beira"}},
        {"Tondela", {"Carregal do Sal", "Santa Comba Dão"}},
        {"Viseu", {"Vila Nova de Paiva", "Castro Daire", "Mangualde"}},
        {"Vouzela", {"Oliveira de Frades"}},
		{"São João da Pesqueira", {"Carrazeda de Ansiães"}},
        {"Vila Nova de Paiva", {"Moimenta da Beira", "Tarouca", "Castro Daire", "Viseu", "Sátão"}}

    };
    /*std::map<std::string, std::vector<std::string>> neighbors = {
        {"1", {"2", "3"}},
        {"2", {"1", "4"}},
        {"3", {"1", "4"}},
        {"4", {"2", "3", "5"}},

        {"5", {"4", "6", "7"}},
        {"6", {"5"}},
        {"7", {"5", "8"}},

        {"8", {"7", "10", "9"}},
        {"9", {"8", "10"}},
        {"10", {"8", "9"}}
    };*/
    return neighbors;
}